### ISSUE TITLE
VLC Chrome extension not working

### ISSUE THREAD

**Issue by fernadosilva** [bazuchan/pythonvlm#3]
Since a few days ago (possibly 1st January 2023) it seems that the VLC extension is not producing the correct camera altitude from Litchi Mission Hub missions, possibly due to some problem retrieving altitude data. More information on https://forum.flylitchi.com/t/mission-export-as-vlm-to-view-flight-in-google-earth-pro-bug/8137/4 

Is it possible to try to check this issue?

**Comment by bazuchan** [comment]
Should be fixed since yesterday
