### ISSUE TITLE
vlm.py GOOGLEKEY global ?

### ISSUE THREAD

**Issue by Carpintonto** [bazuchan/pythonvlm#4]
Neither Chrome nor Firefox Litchi Virtual Mission browser extensions have been working for me since Saturday April 22.
I would be completely happy to use vlm.py  but getting errors suggesting I need a google API key, I got one.

do I just declare a global GOOGLEKEY here in vlm.py?

class Elevation(object):
    GOOGLEAPI = 'https://maps.googleapis.com/maps/api/elevation/json'
    OPENAPI = 'https://api.open-elevation.com/api/v1/lookup'
    MAXPERREQ = 100

**Comment by Carpintonto** [comment]
class Elevation(object):
I'm getting better errors now with    

```
GOOGLEAPI = 'https://maps.googleapis.com/maps/api/elevation/json'
    OPENAPI = 'https://api.open-elevation.com/api/v1/lookup'
    MAXPERREQ = 100
    GOOGLEKEY = 'MyOwnReallyBigKeyHere'

    def __init__(self, key='', openapi=''):
        self.key = key or self.GOOGLEKEY
        self.openapi = openapi or self.OPENAPI
```

I am not seeing the API key errors, but 

```
Traceback (most recent call last):
  File "./vlm.py", line 469, in <module>
    c.run(args.csvfile, args.kmlfile)
  File "./vlm.py", line 439, in run
    self.smooth()
  File "./vlm.py", line 257, in smooth
    sp.Heading = WayPoint.to360(wp.Heading + diffhead * wd / (wd+nd))
ZeroDivisionError: float division by zero
```

Something in my data needs to be different?

I think it would be helpful to have a textbox in the browser extensions' management interfaces to accept API key entries.

**Comment by bazuchan** [comment]
Check `./vlm.py --help` it has an option to pass google api key. Or if you are using webvlm, you can pass environment variable `GOOGLEKEY`.

I have tested a couple of my missions and everything working as expected. Would you mind sharing mission csv, so I could look into it?

**Comment by Carpintonto** [comment]
Thanks bazuchan
The original csv is attached and also [available here](https://luckyantler.com/drones/BrooklaneMarys/).

I may have discovered the problem. I had two waypoints, 9 and 10, too close to each other.  Litichi refused to fly until I removed one of them. This csv is the original with that error.  It just seems to me that could cause a divide by zero error.

[BrooklaneMarys.csv.kml](https://luckyantler.com/drones/BrooklaneMarys/BrooklaneMarys.csv.kml)
generated at http://shell.tor.hu/csv2kml/ is from the original csv attached.

[BrooklaneMarys.csv](https://github.com/bazuchan/pythonvlm/files/11323797/BrooklaneMarys.csv)

**Comment by Carpintonto** [comment]
vlm.py works perfectly!  Thanks for your help.  

Now it seems the Mission Hub is caching the csv exports.  
The hub renders the corrected mission in the browser, 
but I'm still getting the csv of the uncorrected mission even after flushing my browser cache.
The exported [kml of the corrected mission](https://luckyantler.com/drones/BrooklaneMarys/BrooklaneMarys.kml) is correct.

**Comment by bazuchan** [comment]
> I may have discovered the problem. I had two waypoints, 9 and 10, too close to each other. Litichi refused to fly until I removed one of them.

It was indeed the reason. I suspected it and was going to fix it, but since litchi refuses to fly it too, I will keep it as is.

**Comment by Carpintonto** [comment]
I say absolutely leave it.  
Your error trapping occurs far earlier in the planning to actual flight process.
Plus with the script, the error messages are more indicative of what problems may be.
Good job!
